package com.advocacia.enums;

import com.fasterxml.jackson.annotation.JsonValue;

public enum TipoAcao {
    
    ABERTURA_REGISTRO_TESTAMENTO("Abertura, Registro e Cumprimento de Testamento"),
    ANULATORIA_CLAUSULAS_CONVENCIONAIS("Ação Anulatória de Cláusulas Convencionais"),
    CAUTELAR("Ação Cautelar"),
    CIVIL_COLETIVA("Ação Civil Coletiva"),
    DANO_MORAL("Ação de Dano Moral"),
    CIVIL_ORIGINARIA("Ação Civil Originária"),
    CIVIL_PUBLICA("Ação Civil Pública"),
    ALIMENTOS("Ação de Alimentos"),
    CUMPRIMENTO("Ação de Cumprimento"),
    IMPROBIDADE_ADMINISTRATIVA("Ação de Improbidade Administrativa"),
    IMPUGNACAO_MANDATO_ELETIVO("Ação de Impugnação de Mandato Eletivo"),
    DECLARATORIA_CONSTITUCIONALIDADE("Ação Declaratória de Constitucionalidade"),
    DIRETA_INCONSTITUCIONALIDADE("Ação Direta de Inconstitucionalidade"),
    ORDINARIA_REGRESSIVA("Ação Ordinária Regressiva"),
    ORIGINARIA("Ação Originária"),
    ORIGINARIA_ESPECIAL("Ação Originária Especial"),
    PENAL("Ação Penal"),
    PENAL_PROCEDIMENTO_ORDINARIO("Ação Penal - Procedimento Ordinário"),
    PENAL_PROCEDIMENTO_SUMARIO("Ação Penal - Procedimento Sumário"),
    PENAL_PROCEDIMENTO_SUMARISSIMO("Ação Penal - Procedimento Sumaríssimo"),
    PENAL_COMPETENCIA_JURI("Ação Penal de Competência do Júri"),
    PENAL_ELEITORAL("Ação Penal Eleitoral"),
    PENAL_MILITAR_ORDINARIO("Ação Penal Militar - Procedimento Ordinário"),
    REGRESSIVA("Ação Regressiva"),
    RESCISORIA("Ação Rescisória"),
    TRABALHISTA_RITO_ORDINARIO("Ação Trabalhista - Rito Ordinário"),
    TRABALHISTA_RITO_SUMARIO("Ação Trabalhista - Rito Sumário (Alçada)"),
    TRABALHISTA_RITO_SUMARISSIMO("Ação Trabalhista - Rito Sumaríssimo"),
    ACOLHIMENTO_EMBARGOS_DECLARACAO("Acolhimento de Embargos de Declaração"),
    ADOCAO("Adoção"),
    ADOCAO_DESTITUICAO_PODER_FAMILIAR("Adoção c/c Destituição do Poder Familiar"),
    ADVERTENCIA("Advertência"),
    AGRAVO("Agravo"),
    AGRAVO_EXECUCAO_PENAL("Agravo de Execução Penal"),
    AGRAVO_INSTRUMENTO("Agravo de Instrumento"),
    AGRAVO_INSTRUMENTO_AGRAVO_PETICAO("Agravo de Instrumento em Agravo de Petição"),
    AGRAVO_INSTRUMENTO_RECURSO_MANDADO_SEGURANCA("Agravo de Instrumento em Recurso de Mandado de Segurança"),
    AGRAVO_INSTRUMENTO_RECURSO_REVISTA("Agravo de Instrumento em Recurso de Revista"),
    AGRAVO_INSTRUMENTO_RECURSO_ESPECIAL("Agravo de Instrumento em Recurso Especial"),
    AGRAVO_INSTRUMENTO_RECURSO_EXTRAORDINARIO("Agravo de Instrumento em Recurso Extraordinário"),
    AGRAVO_INSTRUMENTO_RECURSO_ORDINARIO("Agravo de Instrumento em Recurso Ordinário"),
    AGRAVO_INSTRUMENTO_RECURSO_ORDINARIO_STF("Agravo de Instrumento em Recurso Ordinário para o STF"),
    AGRAVO_PETICAO("Agravo de Petição"),
    AGRAVO_REGIMENTAL("Agravo Regimental"),
    ALIENACAO_BENS_ACUSADO("Alienação de Bens do Acusado"),
    ALIENACAO_JUDICIAL_BENS("Alienação Judicial de Bens"),
    ALIMENTOS_LEI_ESPECIAL("Alimentos - Lei Especial Nº 5.478/68"),
    ALIMENTOS_PROVISIONAIS("Alimentos - Provisionais"),
    ALTERACAO_REGIME_BENS("Alteração do Regime de Bens"),
    ALVARA_JUDICIAL("Alvará Judicial"),
    ALVARA_JUDICIAL_LEI_6858("Alvará Judicial - Lei 6858/80"),
    ANISTIA("Anistia"),
    ANTECIPACAO_TUTELA("Antecipação de tutela"),
    ANULACAO_SUBSTITUICAO_TITULOS("Anulação e Substituição de Títulos ao Portador"),
    APELACAO("Apelação"),
    APELACAO_REEXAME_NECESSARIO("Apelação / Reexame Necessário"),
    APELACAO_CIVEL("Apelação Cível"),
    APELACAO_CRIMINAL("Apelação Criminal"),
    APELACAO_MANDADO_SEGURANCA("Apelação em Mandado de Segurança"),
    APENSAMENTO("Apensamento"),
    APREENSAO_TITULOS("Apreensão de Títulos"),
    APREENSAO_EMBARCACOES("Apreensão de Embarcações"),
    APREENSAO_DEPOSITO_COISA_VENDIDA("Apreensão e Depósito de Coisa Vendida com Reserva de Domínio"),
    APURACAO_INFRACAO_ADMINISTRATIVA("Apuração de Infração Administrativa às Normas de Proteção à Criança ou Adolescente"),
    APURACAO_IRREGULARIDADES_ENTIDADES("Apuração de Irregularidades em Entidades de Atendimento"),
    ARGUICAO_DESCUMPRIMENTO_PRECEITO_FUNDAMENTAL("Arguição de Descumprimento de Preceito Fundamental"),
    ARGUICAO_INCONSTITUCIONALIDADE("Arguição de Inconstitucionalidade"),
    ARGUICAO_RELEVANCIA("Arguição de Relevância"),
    ARGUICAO_SUSPEICAO("Arguição de Suspeição"),
    ARRECADACAO_COISAS_VAGAS("Arrecadação das Coisas Vagas"),
    ARRESTO("Arresto"),
    ARRESTO_HIPOTECA_LEGAL("Arresto / Hipoteca Legal"),
    ARRIBADAS_FORCADAS("Arribadas Forçadas"),
    ARROLAMENTO_COMUM("Arrolamento Comum"),
    ARROLAMENTO_BENS("Arrolamento de Bens"),
    ARROLAMENTO_SUMARIO("Arrolamento Sumário"),
    ASSEDIO_MORAL("Assédio Moral"),
    ATENTADO("Atentado"),
    AUTO_APREENSAO_FLAGRANTE("Auto de Apreensão em Flagrante"),
    AUTO_PRISAO_FLAGRANTE("Auto de Prisão em Flagrante"),
    AUTORIZACAO_JUDICIAL("Autorização judicial"),
    AUXILIO_INCAPACIDADE_PERMANENTE("Auxílio por Incapacidade Permanente"),
    AUXILIO_INCAPACIDADE_TEMPORARIA("Auxílio por Incapacidade Temporária"),
    AUXILIO_ACIDENTE("Auxílio-acidente"),
    AVALIACAO_DEPENDENCIA_DROGAS("Avaliação para atestar dependência de drogas"),
    AVARIA_CARGO_SEGURADOR("Avaria a Cargo do Segurador"),
    AVARIAS("Avarias"),
    AVERIGUACAO_PATERNIDADE("Averiguação de Paternidade"),
    AVOCATORIA("Avocatória"),
    BAIXA_DEFINITIVA("Baixa Definitiva"),
    BOLETIM_OCORRENCIA_CIRCUNSTANCIADA("Boletim de Ocorrência Circunstanciada"),
    BPC_DEFICIENTE("BPC - Deficiente"),
    BPC_IDOSO("BPC - Idoso"),
    BUSCA_APREENSAO("Busca e Apreensão"),
    BUSCA_APREENSAO_ALIENACAO_FIDUCIARIA("Busca e Apreensão em Alienação Fiduciária"),
    CANCELAMENTO_DISTRIBUICAO("Cancelamento da distribuição"),
    CANCELAMENTO_NATURALIZACAO("Cancelamento de Naturalização"),
    CANCELAMENTO_REGISTRO_PARTIDO_POLITICO("Cancelamento de Registro de Partido Político"),
    CARTA_ORDEM("Carta de Ordem"),
    CARTA_PRECATORIA("Carta Precatória"),
    CARTA_ROGATORIA("Carta Rogatória"),
    CARTA_TESTEMUNHAVEL("Carta Testemunhável"),
    CAUCAO("Caução"),
    CAUTELAR_FISCAL("Cautelar Fiscal"),
    CAUTELAR_INOMINADA("Cautelar Inominada"),
    COBRANCA_CEDULA_CREDITO_INDUSTRIAL("Cobrança de Cédula de Crédito Industrial"),
    COMPROMISSO_ARBITRAL("Compromisso Arbitral"),
    COMUNICACAO("Comunicação"),
    COMUTACAO_PENA("Comutação de Pena"),
    CONCESSAO_APOSENTADORIA("Concessão de Aposentadoria"),
    CONCLUSAO("Conclusão"),
    CONFIRMACAO_TESTAMENTO("Confirmação de Testamento"),
    CONFLITO_ATRIBUICAO("Conflito de atribuição"),
    CONFLITO_ATRIBUICOES("Conflito de Atribuições"),
    CONFLITO_COMPETENCIA("Conflito de Competência"),
    CONFLITO_JURISDICAO("Conflito de Jurisdição"),
    CONHECIMENTO_PARTE_NAO_PROVIMENTO("Conhecimento em Parte e Não-Provimento"),
    CONHECIMENTO_PARTE_PROVIMENTO("Conhecimento em Parte e Provimento"),
    CONHECIMENTO_PARTE_PROVIMENTO_PARTE("Conhecimento em Parte e Provimento em Parte"),
    CONSELHO_JUSTIFICACAO("Conselho de Justificação"),
    CONSIGNACAO_PAGAMENTO("Consignação em Pagamento"),
    CONSIGNATORIA_ALUGUEIS("Consignatória de Aluguéis"),
    CONSULTA("Consulta"),
    CONTRAPROTEST0_JUDICIAL("Contraprotesto Judicial"),
    CONTRIBUICAO_TAXA_ASSISTENCIAL("Contribuição / Taxa Assistencial"),
    CONTRIBUICAO_CONFEDERATIVA("Contribuição Confederativa"),
    CONVENCAO_PARTES("Convenção das Partes"),
    CONVERSAO_AGRAVO_INSTRUMENTO_AGRAVO_RETIDO("Conversão de Agravo de Instrumento em Agravo Retido"),
    CONVERSAO_PENA("Conversão de Pena"),
    CONVERSAO_SEPARACAO_JUDICIAL_DIVORCIO("Conversão de Separação Judicial em Divórcio"),
    CORREICAO("Correição"),
    CORREICAO_EXTRAORDINARIA("Correição Extraordinária"),
    CORREICAO_ORDINARIA("Correição Ordinária"),
    CORREICAO_PARCIAL("Correição Parcial"),
    CORREICAO_PARCIAL_RECLAMACAO("Correição Parcial ou Reclamação Correicional"),
    CRIACAO_ZONA_ELEITORAL("Criação de Zona Eleitoral ou Remanejamento"),
    CRIMES_AMBIENTAIS("Crimes Ambientais"),
    CRIMES_PROPRIEDADE_IMATERIAL("Crimes Contra a Propriedade Imaterial"),
    CRIMES_PROPRIEDADE_INDUSTRIAL("Crimes Contra a Propriedade Industrial"),
    CRIMES_PROPRIEDADE_INTELECTUAL("Crimes Contra a Propriedade Intelectual"),
    CRIMES_CALUNIA_INJURIA_DIFAMACAO("Crimes de Calúnia, Injúria e Difamação de Competência do Juiz Singular"),
    CRIMES_IMPRENSA("Crimes de Imprensa"),
    CUMPRIMENTO_SENTENCA("Cumprimento de sentença"),
    CUMPRIMENTO_PROVISORIO_DECISAO("Cumprimento Provisório de Decisão"),
    DECLARACAO_AUSENCIA("Declaração de Ausência"),
    DECLARATORIA_CONSTITUCIONALIDADE_2("Declaratória de Constitucionalidade"),
    DECRETACAO_FALENCIA("Decretação de falência"),
    DELIBERACAO_PARTILHA("Deliberação da partilha"),
    DEMARCACAO_DIVISAO("Demarcação / Divisão"),
    DENUNCIA("Denúncia"),
    DEPOSITARIO_INFIEL("Depositário infiel"),
    DEPOSITO("Depósito"),
    DEPOSITO_LEI_8866("Depósito da Lei 8.866/94"),
    DESAFORAMENTO_JULGAMENTO("Desaforamento de Julgamento"),
    DESAPENSAMENTO("Desapensamento"),
    DESAPROPRIACAO("Desapropriação"),
    DESAPROPRIACAO_IMOVEL_RURAL_INTERESSE_SOCIAL("Desapropriação Imóvel Rural por Interesse Social"),
    DESERCAO_OFICIAL("Deserção de Oficial"),
    DESERCAO_PRACA("Deserção de Praça"),
    DESPEJO("Despejo"),
    DESPEJO_FALTA_PAGAMENTO("Despejo por Falta de Pagamento"),
    DESPEJO_FALTA_PAGAMENTO_COBRANCA("Despejo por Falta de Pagamento Cumulado Com Cobrança"),
    DESTINACAO("Destinação"),
    DESTINACAO_PARCIAL("Destinação Parcial"),
    DETERMINACAO_ARQUIVAMENTO_PROCEDIMENTOS("Determinação de arquivamento de procedimentos investigatórios"),
    DIREITO_VISITA("Direito de visita"),
    DIRETA_INCONSTITUCIONALIDADE_2("Direta de Inconstitucionalidade"),
    DISCRIMINATORIA("Discriminatória"),
    DISSIDIO_COLETIVO("Dissídio Coletivo"),
    DISSIDIO_COLETIVO_GREVE("Dissídio Coletivo de Greve"),
    DISSOLUCAO_LIQUIDACAO_SOCIEDADE("Dissolução e Liquidação de Sociedade"),
    DIVORCIO_CONSENSUAL("Divórcio Consensual"),
    DIVORCIO_LITIGIOSO("Divórcio Litigioso"),
    DUVIDA("Dúvida"),
    EFEITO_SUSPENSIVO("Efeito Suspensivo"),
    ELEICAO("Eleição"),
    EMANCIPACAO("Emancipação"),
    EMBARGOS("Embargos"),
    EMBARGOS_ADJUDICACAO("Embargos à Adjudicação"),
    EMBARGOS_ARREMETACAO("Embargos à Arrematação"),
    EMBARGOS_EXECUCAO("Embargos à Execução"),
    EMBARGOS_EXECUCAO_ACAO_RECISORIA("Embargos à Execução em Ação Recisoria"),
    EMBARGOS_EXECUCAO_MANDADO_SEGURANCA("Embargos à Execução em Mandado de Segurança"),
    EMBARGOS_EXECUCAO_MEDIDA_CAUTELAR("Embargos à Execução em Medida Cautelar"),
    EMBARGOS_EXECUCAO_FISCAL("Embargos à Execução Fiscal"),
    EMBARGOS_DECLARACAO("Embargos de Declaração"),
    EMBARGOS_DIVERGENCIA("Embargos de Divergência"),
    EMBARGOS_DIVERGENCIA_RECURSO_MANDADO_SEGURANCA("Embargos de Divergência em Recurso de Mandado de Segurança"),
    EMBARGOS_DIVERGENCIA_RECURSO_ESPECIAL("Embargos de Divergência em Recurso Especial"),
    EMBARGOS_RETENCAO_BENFEITORIAS("Embargos de Retenção por Benfeitorias"),
    EMBARGOS_TERCEIRO("Embargos de Terceiro"),
    EMBARGOS_ACUSADO("Embargos do Acusado"),
    EMBARGOS_ACAO_PENAL_MILITAR("Embargos em Ação Penal Militar"),
    EMBARGOS_AGRAVO_INSTRUMENTO("Embargos em Agravo de Instrumento"),
    EMBARGOS_INFRINGENTES("Embargos Infringentes"),
    EMBARGOS_INFRINGENTES_NULIDADE("Embargos Infringentes e de Nulidade"),
    EMBARGOS_INFRINGENTES_ACAO_RESCISORIA("Embargos Infringentes em Ação Rescisória"),
    EMBARGOS_INFRINGENTES_APELACAO_CIVEL("Embargos Infringentes em Apelação Cível"),
    EMBARGOS_REMETIDOS("Embargos Remetidos"),
    ESPECIALIZACAO_HIPOTECA_LEGAL("Especialização de Hipoteca Legal"),
    EXCECAO_VERDADE("Exceção da Verdade"),
    EXCECAO_COISA_JULGADA("Exceção de Coisa Julgada"),
    EXCECAO_ILEGITIMIDADE_PARTE("Exceção de Ilegitimidade de Parte"),
    EXCECAO_IMPEDIMENTO("Exceção de Impedimento"),
    EXCECAO_INCOMPETENCIA("Exceção de Incompetência"),
    EXCECAO_INCOMPETENCIA_JUIZO("Exceção de Incompetência de Juízo"),
    EXCECAO_LITISPENDENCIA("Exceção de Litispendência"),
    EXCECAO_SUSPEICAO("Exceção de Suspeição"),
    EXCESSO_DESVIO("Excesso ou Desvio"),
    EXECUCAO_CONTRA_FAZENDA_PUBLICA("Execução Contra a Fazenda Pública"),
    EXECUCAO_PENA("Execução da Pena"),
    EXECUCAO_ALIMENTOS("Execução de Alimentos"),
    EXECUCAO_CERTIDAO_CREDITO_JUDICIAL("Execução de Certidão de Crédito Judicial"),
    EXECUCAO_MEDIDA_SEGURANCA("Execução de Medida de Segurança"),
    EXECUCAO_MULTA("Execução de Multa"),
    EXECUCAO_TERMO_AJUSTE_CONDUTA("Execução de Termo de Ajuste de Conduta"),
    EXECUCAO_TERMO_CONCILIACAO_CCP("Execução de Termo de Conciliação de CCP"),
    EXECUCAO_TITULO_EXTRAJUDICIAL("Execução de Título Extrajudicial"),
    EXECUCAO_ACAO_RESCISORIA("Execução em Ação Rescisória"),
    EXECUCAO_MANDADO_SEGURANCA("Execução em Mandado de Segurança"),
    EXECUCAO_MEDIDA_CAUTELAR("Execução em Medida Cautelar"),
    EXECUCAO_SENTENCA_ESTRANGEIRA("Execução em Sentença Estrangeira"),
    EXECUCAO_SENTENCA_ESTRANGEIRA_CONTESTADA("Execução em Sentença Estrangeira Contestada"),
    EXECUCAO_FISCAL("Execução Fiscal"),
    EXECUCAO_FRUSTRADA("Execução Frustrada"),
    EXECUCAO_HIPOTECARIA_SISTEMA_FINANCEIRO_HABITACAO("Execução Hipotecária do Sistema Financeiro da Habitação"),
    EXECUCAO_PROVISORIA("Execução Provisória"),
    EXECUCAO_PROVISORIA_AUTOS_SUPLEMENTARES("Execução Provisória em Autos Suplementares"),
    EXIBICAO("Exibição"),
    EXIBICAO_DOCUMENTO_COISA("Exibição de Documento ou Coisa"),
    EXPEDICAO_DOCUMENTO("Expedição de documento"),
    EXPROPRIACAO_LEI_8257("Expropriação da Lei 8.257/91"),
    EXTINCAO_EXECUCAO_CUMPRIMENTO_SENTENCA("Extinção da execução ou do cumprimento da sentença"),
    EXTINCAO_OBRIGACOES_FALIDO("Extinção das obrigações do falido"),
    EXTRADICAO("Extradição"),
    FORCA_MAIOR("Força maior"),
    GUARDA("Guarda"),
    HABEAS_CORPUS("Habeas Corpus"),
    HABEAS_DATA("Habeas Data"),
    HABILITACAO("Habilitação"),
    HABILITACAO_CREDITO("Habilitação de Crédito"),
    HABILITACAO_ADOCAO("Habilitação para Adoção"),
    HABILITACAO_CASAMENTO("Habilitação para Casamento"),
    HERANCA_JACENTE("Herança Jacente"),
    HOMOLOGACAO_TRANSACAO_EXTRAJUDICIAL("Homologação de Transação Extrajudicial"),
    HOMOLOGACAO_PENHOR_LEGAL("Homologação do Penhor Legal"),
    IMPUGNACAO_CUMPRIMENTO_DECISAO("Impugnação ao Cumprimento de Decisão"),
    IMPUGNACAO_CUMPRIMENTO_SENTENCA("Impugnação ao Cumprimento de Sentença"),
    IMPUGNACAO_PEDIDO_ASSISTENCIA("Impugnação ao Pedido de Assistência Litisconsorcial ou Simples"),
    IMPUGNACAO_VALOR_CAUSA("Impugnação ao Valor da Causa"),
    IMPUGNACAO_ASSISTENCIA_JUDICIARIA("Impugnação de Assistência Judiciária"),
    IMPUGNACAO_CREDITO("Impugnação de Crédito"),
    INCIDENTE_DESLOCAMENTO_COMPETENCIA("Incidente de Deslocamento de Competência"),
    INCIDENTE_FALSIDADE("Incidente de Falsidade"),
    INCIDENTE_INSANIDADE_MENTAL("Incidente de Insanidade Mental"),
    INCIDENTE_SANIDADE_MENTAL("Incidente de Sanidade Mental"),
    INCIDENTE_UNIFORMIZACAO_JURISPRUDENCIA("Incidente de Uniformização de Jurisprudência"),
    INCLUSAO_PAUTA("Inclusão em pauta"),
    INDULTO("Indulto"),
    INQUERITO("Inquérito"),
    INQUERITO_ADMINISTRATIVO("Inquérito Administrativo"),
    INQUERITO_APURACAO_FALTA_GRAVE("Inquérito para Apuração de Falta Grave"),
    INQUERITO_POLICIAL("Inquérito Policial"),
    INQUERITO_POLICIAL_ESPECIAL("Inquérito Policial Especial"),
    INSANIDADE_MENTAL_ACUSADO("Insanidade Mental do Acusado"),
    INSOLVENCIA_REQUERIDA_CREDOR("Insolvência Requerida pelo Credor"),
    INSOLVENCIA_REQUERIDA_DEVEDOR_ESPOLIO("Insolvência Requerida pelo Devedor ou pelo Espólio"),
    INSPECAO("Inspeção"),
    INSTRUCAO("Instrução"),
    INSTRUCAO_RESCISORIA("Instrução de Rescisória"),
    INSUBISSAO("Insubmissão"),
    INTERDICAO("Interdição"),
    INTERDITO_PROIBITORIO("Interdito Proibitório"),
    INTERNACAO_ATIVIDADES_EXTERNAS("Internação com Atividades Externas"),
    INTERNACAO_SEM_ATIVIDADES_EXTERNAS("Internação sem Atividades Externas"),
    INTERPELACAO("Interpelação"),
    INTERPELACAO_JUDICIAL("Interpelação Judicial"),
    INTERVENCAO_MUNICIPIO("Intervenção em Município"),
    INTERVENCAO_FEDERAL("Intervenção Federal"),
    INTRUCAO_PROVISORIA_DESERCAO("Intrução Provisória de Deserção"),
    INVENTARIO("Inventário"),
    INVESTIGACAO_CONTRA_MAGISTRADO("Investigação contra magistrado"),
    JUSTIFICACAO("Justificação"),
    JUSTIFICACAO_DINHEIRO_RISCO("Justificação de Dinheiro a Risco"),
    LEILAO_PRACA("Leilão ou Praça"),
    LIBERDADE_ASSISTIDA("Liberdade Assistida"),
    LIBERDADE_PROVISORIA("Liberdade Provisória com ou sem fiança"),
    LIQUIDACAO_SENTENCA("Liquidação de Sentença"),
    LIQUIDACAO_ARTIGOS("Liquidação por Artigos"),
    LIQUIDACAO_PROVISORIA_ARBITRAMENTO("Liquidação Provisória por Arbitramento"),
    LIQUIDACAO_PROVISORIA_ARTIGOS("Liquidação Provisória por Artigos"),
    LISTA_TRIPLICE("Lista Tríplice"),
    LIVRAMENTO_CONDICIONAL("Livramento Condicional"),
    MANDADO("Mandado"),
    MANDADO_INJUNCAO("Mandado de Injunção"),
    MANDADO_SEGURANCA("Mandado de Segurança"),
    MANDADO_SEGURANCA_COLETIVO("Mandado de Segurança Coletivo"),
    MEDIDA_CAUTELAR("Medida Cautelar"),
    MEDIDAS_PROTECAO_CRIANCA_ADOLESCENTE("Medidas de Proteção à Criança e Adolescente"),
    MEDIDAS_INVESTIGATORIAS_ORGANIZACOES_CRIMINOSAS("Medidas Investigatórias Sobre Organizações Criminosas"),
    MEDIDAS_PROTETIVAS_ESTATUTO_IDOSO("Medidas Protetivas - Estatuto do Idoso"),
    MEDIDAS_PROTETIVAS_URGENCIA_MARIA_PENHA("Medidas Protetivas de urgência (Lei Maria da Penha)"),
    MONITORIA("Monitória"),
    MORTE_AGENTE("Morte do agente"),
    NAO_DECRETACAO_FALENCIA("Não-Decretação de Falência"),
    NAO_PROVIMENTO("Não-Provimento"),
    NATURALIZACAO("Naturalização"),
    NEGACAO_SEGUIMENTO("Negação de Seguimento"),
    NOMEACAO_ADVOGADO("Nomeação de Advogado"),
    NOTICIA_CRIME("Notícia-Crime"),
    NOTIFICACAO("Notificação"),
    NOTIFICACAO_EXPLICACOES("Notificação para Explicações"),
    NOTIFICACAO_EXPLICACOES_LEI_IMPRENSA("Notificação para Explicações (Lei de Imprensa)"),
    NUNCIACAO_OBRA_NOVA("Nunciação de Obra Nova"),
    OBRIGACAO_REPARAR_DANO("Obrigação de Reparar o Dano"),
    OFICIO("Ofício"),
    OPOSICAO("Oposição"),
    ORDENACAO_ENTREGA_AUTOS("Ordenação de entrega de autos"),
    ORGANIZACAO_FISCALIZACAO_FUNDACAO("Organização e Fiscalização de Fundação"),
    OUTRAS_MEDIDAS_PROVISIONAIS("Outras medidas provisionais"),
    OUTROS_PROCEDIMENTOS_JURISDICAO_VOLUNTARIA("Outros procedimentos de jurisdição voluntária"),
    PAGAMENTO_INTEGRAL_DEBITO("Pagamento integral do débito"),
    PARALISACAO_NEGLIGENCIA_PARTES("Paralisação por negligência das partes"),
    PEDIDO_ARQUIVAMENTO_REPRESENTACAO_CRIMINAL("Pedido de Arquivamento em Representação Criminal"),
    PEDIDO_AVOCACAO("Pedido de Avocação"),
    PEDIDO_BUSCA_APREENSAO_CRIMINAL("Pedido de Busca e Apreensão Criminal"),
    PEDIDO_DESAFORAMENTO("Pedido de Desaforamento"),
    PEDIDO_PRISAO_PREVENTIVA("Pedido de Prisão Preventiva"),
    PEDIDO_PRISAO_TEMPORARIA("Pedido de Prisão Temporária"),
    PEDIDO_PRISAO_LIBERDADE_VIGIADA_EXPULSAO("Pedido de Prisão/ Liberdade Vigiada para Fins de Expulsão"),
    PEDIDO_PROVIDENCIAS("Pedido de Providências"),
    PEDIDO_QUEBRA_SIGILO_DADOS_TELEFONICO("Pedido de Quebra de Sigilo de Dados e/ou Telefônico"),
    PEDIDO_RESPOSTA_RETIFICACAO_LEI_IMPRENSA("Pedido de Resposta ou Retificação da Lei de Imprensa"),
    PEDIDO_REVISAO_VALOR_CAUSA("Pedido de Revisão do Valor da Causa"),
    PEDIDO_UNIFORMIZACAO_INTERPRETACAO_LEI_FEDERAL("Pedido de Uniformização de Interpretação de Lei Federal"),
    PENSAO_MORTE("Pensão por Morte"),
    PERDA_SUSPENSAO_RESTABELECIMENTO_PODER_FAMILIAR("Perda ou Suspensão ou Restabelecimento do Poder Familiar"),
    PEREMPCAO_LITISPENDENCIA_COISA_JULGADA("Perempção, litispendência ou coisa julgada"),
    PERMISSAO_SAIDA("Permissão de saída"),
    PETICAO("Petição"),
    POSSE_NOME_NASCITURO("Posse em Nome do Nascituro"),
    PRE_EXECUTIVIDADE("Pré-executividade"),
    PRECATORIO("Precatório"),
    PRESCRICAO_DECADENCIA_PEREMPCAO("Prescrição, decadência ou perempção"),
    PRESTACAO_CONTAS("Prestação de Contas"),
    PRESTACAO_CONTAS_EXIGIDAS("Prestação de Contas - Exigidas"),
    PRESTACAO_CONTAS_OFERECIDAS("Prestação de Contas - Oferecidas"),
    PRESTACAO_SERVICOS_COMUNIDADE("Prestação de Serviços a Comunidade"),
    PRISAO("Prisão"),
    PRISAO_PREVENTIVA_EXTRADICAO("Prisão Preventiva para Extradição"),
    PROCEDENCIA_PARTE("Procedência em Parte"),
    PROCEDIMENTO_JUIZADO_ESPECIAL_CIVEL("Procedimento do Juizado Especial Cível"),
    PROCEDIMENTO_JUIZADO_ESPECIAL_CRIMINAL_SUMARISSIMO("Procedimento do Juizado Especial Criminal - Sumariíssimo"),
    PROCEDIMENTO_ESPECIAL_LEI_ANTITOXICOS("Procedimento Especial da Lei Antitóxicos"),
    PROCEDIMENTO_ESPECIAL_CRIMES_ABUSO_AUTORIDADE("Procedimento Especial dos Crimes de Abuso de Autoridade"),
    PROCEDIMENTO_INVESTIGATORIO_MP("Procedimento Investigatório do MP (Peças de Informação)"),
    PROCEDIMENTO_ORDINARIO("Procedimento ordinário"),
    PROCEDIMENTO_SUMARIO("Procedimento Sumário"),
    PROCESSO_ADMINISTRATIVO("Processo Administrativo"),
    PROCESSO_ADMINISTRATIVO_DISCIPLINAR_MAGISTRADO("Processo Administrativo Disciplinar em face de Magistrado"),
    PROCESSO_ADMINISTRATIVO_DISCIPLINAR_SERVIDOR("Processo Administrativo Disciplinar em face de Servidor"),
    PROCESSO_CRIME("Processo Crime"),
    PROCESSO_APURACAO_ATO_INFRACIONAl("Processo de Apuração de Ato Infracional"),
    PROCESSO_JUDICIAL("Processo Judicial"),
    PROCESSO_SUMARIO_DETENCAO("Processo Sumário (Detenção)"),
    PROGRESSAO_REGIME("Progressão de regime"),
    PROTESTO("Protesto"),
    PROTESTO_FORMADO_BORDO("Protesto Formado a Bordo"),
    PROTESTO_NOVO_JURI("Protesto por Novo Júri"),
    PROTOCOLO_PETICAO("Protocolo de Petição"),
    PROVIDENCIA("Providência"),
    PROVIDENCIA_PARTE("Provimento em Parte"),
    PUBLICACAO("Publicação"),
    QUEIXA_CRIME("Queixa Crime"),
    QUESTAO_ORDEM("Questão de Ordem"),
    REABILITACAO("Reabilitação"),
    RECEBIMENTO_EMBARGOS_EXECUCAO("Recebimento de Embargos à Execução"),
    RECLAMACAO("Reclamação"),
    RECLAMACAO_DISCIPLINAR("Reclamação Disciplinar"),
    RECUPERACAO_EXTRAJUDICIAL("Recuperação Extrajudicial"),
    RECUPERACAO_JUDICIAL("Recuperação Judicial"),
    RECURSO_ADMINISTRATIVO("Recurso Administrativo"),
    RECURSO_CONTRA_EXPEDICAO_DIPLOMA("Recurso contra Expedição de Diploma"),
    RECURSO_CRIMINAL("Recurso Criminal"),
    RECURSO_APREENSAO_LIVRO("Recurso de Apreensão de Livro"),
    RECURSO_LIQUIDACAO_SENTENCA("Recurso de Liquidação de Sentença"),
    RECURSO_MEDIDA_CAUTELAR("Recurso de Medida Cautelar"),
    RECURSO_MULTA("Recurso de Multa"),
    RECURSO_REVISTA("Recurso de Revista"),
    RECURSO_SENTENCA_CRIMINAL("Recurso de Sentença Criminal"),
    RECURSO_HABEAS_CORPUS("Recurso em Habeas Corpus"),
    RECURSO_HABEAS_DATA("Recurso em Habeas Data"),
    RECURSO_MANDADO_INJUNCAO("Recurso em Mandado de Injunção"),
    RECURSO_MANDADO_SEGURANCA("Recurso em Mandado de Segurança"),
    RECURSO_PROCESSO_ADMINISTRATIVO_DISCIPLINAR_SERVIDOR("Recurso em Processo Administrativo Disciplinar em face de Servidor"),
    RECURSO_SENTIDO_ESTRITO("Recurso em Sentido Estrito"),
    RECURSO_SENTIDO_ESTRITO_EX_OFFICIO("Recurso em sentido estrito/Recurso ex officio"),
    RECURSO_ESPECIAL("Recurso Especial"),
    RECURSO_ESPECIAL_ELEITORAL("Recurso Especial Eleitoral"),
    RECURSO_EXTRAORDINARIO("Recurso Extraordinário"),
    RECURSO_INOMINADO("Recurso Inominado"),
    RECURSO_ORDINARIO("Recurso Ordinário"),
    RECURSO_ORDINARIO_HABEAS_CORPUS("Recurso Ordinário em Habeas Corpus"),
    RECURSO_ORDINARIO_MANDADO_SEGURANCA("Recurso Ordinário em Mandado de Segurança"),
    RECURSO_PREJUDICADO("Recurso prejudicado"),
    REDISPONIBILIZACAO_DIARIO_JUSTICA_ELETRONICO("Redisponibilização no Diário da Justiça Eletrônico"),
    REEXAME_NECESSARIO("Reexame Necessário"),
    REEXAME_NECESSARIO_RECURSO_ORDINARIO("Reexame Necessário / Recurso Ordinário"),
    REFORMA_DECISAO_ANTERIOR("Reforma de decisão anterior"),
    REGISTRO_CASAMENTO_NUNCUPATIVO("Registro de Casamento Nuncupativo"),
    REGISTRO_COMITE_FINANCEIRO("Registro de Comitê Financeiro"),
    REGISTRO_ENTIDADE_SINDICAL("Registro de Entidade Sindical"),
    REGISTRO_ORGAO_PARTIDO_POLITICO_FORMACAO("Registro de Órgão de Partido Político em Formação"),
    REGISTRO_TORRENS("Registro Torrens"),
    REGULAMENTACAO_VISITAS("Regulamentação de Visitas"),
    REGULARIZACAO_REGISTRO_CIVIL("Regularização de Registro Civil"),
    REINTEGRACAO_MANUTENCAO_POSSE("Reintegração / Manutenção de Posse"),
    RELATORIO_INVESTIGACOES("Relatório de Investigações"),
    RELATORIO_FALIMENTAR("Relatório Falimentar"),
    RELAXAMENTO_PRISAO("Relaxamento de Prisão"),
    REMESSA("Remessa"),
    REMICAO("Remição"),
    REMICAO_IMOVEL_HIPOTECADO("Remição do Imóvel Hipotecado"),
    REMOCAO_INVENTARIANTE("Remoção de Inventariante"),
    REMOCAO_MODIFICACAO_DISPENSA_TUTOR_CURADOR("Remoção, modificação e dispensa de tutor ou curador"),
    RENOVATORIA_LOCACAO("Renovatória de Locação"),
    RENUNCIA_QUEIXOSO_PERDAO_ACEITO("Renúncia do queixoso ou perdão aceito"),
    REPRESENTACAO("Representação"),
    REPRESENTACAO_CRIMINAL("Representação Criminal"),
    REPRESENTACAO_DECLARACAO_INDIGNIDADE_INCOMPATIBILIDADE("Representação p/ Declaração de Indignidade/Incompatibilidade"),
    REPRESENTACAO_PERDA_GRADUACAO("Representação p/ Perda da Graduação"),
    REPRESENTACAO_EXCESSO_PRAZO("Representação por Excesso de Prazo"),
    REQUISICAO_INFORMACOES("Requisição de informações"),
    REQUISICAO_PEQUENO_VALOR("Requisição de Pequeno Valor"),
    RESTABELECIMENTO_AUXILIO_INCAPACIDADE_TEMPORARIA("Restabelecimento de Auxílio por Incapacidade Temporária"),
    RESTABELECIMENTO_BENEFICIO_PREVIDENCIARIO("Restabelecimento de Benefício Previdenciário"),
    RESTABELECIMENTO_BPC("Restabelecimento de BPC"),
    RESTABELECIMENTO_PENSAO_MORTE("Restabelecimento de Pensão por Morte"),
    RESTAURACAO_AUTOS("Restauração de Autos"),
    RESTITUICAO_COISAS_APREENDIDAS("Restituição de Coisas Apreendidas"),
    RETIFICACAO_NOME_ESTRANGEIRO("Retificação de Nome Estrangeiro"),
    RETIFICACAO_REGISTRO_IMOVEL("Retificação de Registro de Imóvel"),
    RETIFICACAO_SUPRIMENTO_RESTAURACAO_REGISTRO_CIVIL("Retificação ou Suprimento ou Restauração de Registro Civil"),
    RETRATACAO_AGENTE("Retratação do agente"),
    RETROATIVIDADE_LEI("Retroatividade de lei"),
    REVISAO_CRIMINAL("Revisão Criminal"),
    REVISAO_ELEITORADO("Revisão de Eleitorado"),
    REVISAO_JUDICIAL_DECISAO_CONSELHO_TUTELAR("Revisão Judicial de Decisão do Conselho Tutelar"),
    REVISIONAL_ALUGUEL("Revisional de Aluguel"),
    SALARIO_NATURA("Salário In Natura"),
    SALARIO_MATERNIDADE("Salário-maternidade"),
    SEMILIBERDADE("Semiliberdade"),
    SENTENCA_ARBITRAL("Sentença Arbitral"),
    SENTENCA_ESTRANGEIRA("Sentença Estrangeira"),
    SENTENCA_ESTRANGEIRA_CONTESTADA("Sentença Estrangeira Contestada"),
    SEPARACAO_CONSENSUAL("Separação Consensual"),
    SEPARACAO_LITIGIOSA("Separação Litigiosa"),
    SEQUESTRO("Seqüestro"),
    SESSAO_TRIBUNAL_JURI("Sessão do Tribunal do Júri"),
    SINDICANCIA("Sindicância"),
    SONEGADOS("Sonegados"),
    SUPERVENIENCIA_DOENCA_MENTAL("Superveniência de doença mental"),
    SUPRIMENTO_CAPACIDADE_CONSENTIMENTO_CASAR("Suprimento de Capacidade ou de Consentimento para Casar"),
    SUPRIMENTO_IDADE_CONSENTIMENTO("Suprimento de Idade e/ou Consentimento"),
    SUSPENSAO_CONDICIONAL_PENA("Suspensão Condicional da Pena"),
    SUSPENSAO_CONDICIONAL_PROCESSO("Suspensão Condicional do Processo"),
    SUSPENSAO_DIREITOS("Suspensão de Direitos"),
    SUSPENSAO_EXECUCAO_SENTENCA("Suspensão de Execução de Sentença"),
    SUSPENSAO_LIMINAR("Suspensão de Liminar"),
    SUSPENSAO_LIMINAR_SENTENCA("Suspensão de Liminar e de Sentença"),
    SUSPENSAO_LIMINAR_ANTECIPACAO_TUTELA("Suspensão de Liminar ou Antecipação de Tutela"),
    SUSPENSAO_SEGURANCA("Suspensão de Segurança"),
    SUSPENSAO_TUTELA_ANTECIPADA("Suspensão de Tutela Antecipada"),
    SUSPENSAO_PROCESSO("Suspensão do Processo"),
    TERMO_CIRCUNSTANCIADO("Termo Circunstanciado"),
    TRABALHO_EXTERNO("Trabalho Externo"),
    TRANSFERENCIA_EXECUCAO_PENA("Transferência da Execução da Pena"),
    TRANSFERENCIA_ESTABELECIMENTOS_PENAIS("Transferência entre estabelecimentos penais"),
    TRANSFERENCIA_OUTRO_ESTABELECIMENTO_PENAL("Transferência para outro Estabelecimento Penal"),
    TUTELA("Tutela"),
    TUTELA_DESTITUICAO_PODER_FAMILIAR("Tutela c/c Destituição do Poder Familiar"),
    TUTELA_CURATELA_NOMEACAO("Tutela e Curatela - Nomeação"),
    TUTELA_CURATELA_REMOCAO_DISPENSA("Tutela e Curatela - Remoção e Dispensa"),
    UNIFICACAO_PENAS("Unificação de penas"),
    USUCAPIAO("Usucapião"),
    NULIDADE_DEBITOS("Ação Declaratória de Nulidade de Débitos"),
    INSS("Instituto Nacional do Seguro Social - INSS"),
    REVISAO_CONTRATO("Ação de Revisão de contrato"),
    PRATICAS_ABUSIVAS("Pratica Abusivas"),
    USUFRUTO("Usufruto"),
    UNIAO_ESTAVEL("Ação de reconhecimento e dissolução de união Estável"),
    OUTROS("Outros");

    private String descricao;

    TipoAcao(String descricao) {
        this.descricao = descricao;
    }

    @JsonValue

    public String getDescricao() {
        return descricao;
    }
}
