export const STATUS_PROCESSO_OPTIONS = [
    { value: 'ATIVO', label: 'Ativo' },
    { value: 'ENCERRADO', label: 'Encerrado' },
];
  
export const FASE_PROCESSO_OPTIONS = [
    { value: 'INICIAL', label: 'Fase Inicial' },
    { value: 'AUDIENCIA', label: 'Fase de Audiência' },
    { value: 'CITACAO', label: 'Fase de Citação' },
    { value: 'CONCILIACAO', label: 'Fase de Conciliação' },
    { value: 'CONTESTACAO', label: 'Fase de Contestação' },
    { value: 'SENTENCA', label: 'Fase de Sentença' },
];
  
export const RESULTADO_PROCESSO_OPTIONS = [
    { value: 'Acordo', label: 'Acordo' },
    { value: 'Extinto', label: 'Extinto' },
    { value: 'Improcedente', label: 'Improcedente' },
    { value: 'Parcialmente Procedente', label: 'Parcialmente Procedente' },
    { value: 'Procedente', label: 'Procedente' },
];

export const QUALIFICACAO_OPTIONS = [
    { value: 'Acusado', label: 'Acusado' },
    { value: 'Acusante', label: 'Acusante' },
    { value: 'Adotado', label: 'Adotado' },
    { value: 'Adotante', label: 'Adotante' },
    { value: 'Agravado', label: 'Agravado' },
    { value: 'Agravante', label: 'Agravante' },
    { value: 'Apelado', label: 'Apelado' },
    { value: 'Apelante', label: 'Apelante' },
    { value: 'Autor', label: 'Autor' },
    { value: 'Comunicado', label: 'Comunicado' },
    { value: 'Comunicante', label: 'Comunicante' },
    { value: 'Corrigente', label: 'Corrigente' },
    { value: 'Corrigido', label: 'Corrigido' },
    { value: 'Embargado', label: 'Embargado' },
    { value: 'Embargante', label: 'Embargante' },
    { value: 'Excepto', label: 'Excepto' },
    { value: 'Excipiente', label: 'Excipiente' },
    { value: 'Executado', label: 'Executado' },
    { value: 'Executante', label: 'Executante' },
    { value: 'Expropriado', label: 'Expropriado' },
    { value: 'Expropriante', label: 'Expropriante' },
    { value: 'Impetrado', label: 'Impetrado' },
    { value: 'Impetrante', label: 'Impetrante' },
    { value: 'Impugnado', label: 'Impugnado' },
    { value: 'Impugnante', label: 'Impugnante' },
    { value: 'Interpelado', label: 'Interpelado' },
    { value: 'Interpelante', label: 'Interpelante' },
    { value: 'Inventariado', label: 'Inventariado' },
    { value: 'Inventariante', label: 'Inventariante' },
    { value: 'Noticiado', label: 'Noticiado' },
    { value: 'Noticiante', label: 'Noticiante' },
    { value: 'Notificado', label: 'Notificado' },
    { value: 'Notificante', label: 'Notificante' },
    { value: 'Nunciado', label: 'Nunciado' },
    { value: 'Nunciante', label: 'Nunciante' },
    { value: 'Ofendido', label: 'Ofendido' },
    { value: 'Ofensor', label: 'Ofensor' },
    { value: 'Opoente', label: 'Opoente' },
    { value: 'Oposto', label: 'Oposto' },
    { value: 'Querelado', label: 'Querelado' },
    { value: 'Querelante', label: 'Querelante' },
    { value: 'Reclamado', label: 'Reclamado' },
    { value: 'Reclamante', label: 'Reclamante' },
    { value: 'Recorrente', label: 'Recorrente' },
    { value: 'Recorrido', label: 'Recorrido' },
    { value: 'Representado', label: 'Representado' },
    { value: 'Representante', label: 'Representante' },
    { value: 'Requerente', label: 'Requerente' },
    { value: 'Requerido', label: 'Requerido' },
    { value: 'Réu', label: 'Réu' },
    { value: 'Suscitado', label: 'Suscitado' },
    { value: 'Suscitante', label: 'Suscitante' },
];

export const INSTANCIA_OPTIONS = [
    { value: '1ª Instância', label: '1ª Instância' },
    { value: 'Tribunal de Justiça - Acre', label: 'Tribunal de Justiça - Acre' },
    { value: 'Tribunal de Justiça - Alagoas', label: 'Tribunal de Justiça - Alagoas' },
    { value: 'Tribunal de Justiça - Amapá', label: 'Tribunal de Justiça - Amapá' },
    { value: 'Tribunal de Justiça - Amazonas', label: 'Tribunal de Justiça - Amazonas' },
    { value: 'Tribunal de Justiça - Bahia', label: 'Tribunal de Justiça - Bahia' },
    { value: 'Tribunal de Justiça - Ceará', label: 'Tribunal de Justiça - Ceará' },
    { value: 'Tribunal de Justiça - Distrito Federal', label: 'Tribunal de Justiça - Distrito Federal' },
    { value: 'Tribunal de Justiça - Espírito Santo', label: 'Tribunal de Justiça - Espírito Santo' },
    { value: 'Tribunal de Justiça - Goiás', label: 'Tribunal de Justiça - Goiás' },
    { value: 'Tribunal de Justiça - Maranhão', label: 'Tribunal de Justiça - Maranhão' },
    { value: 'Tribunal de Justiça - Mato Grosso', label: 'Tribunal de Justiça - Mato Grosso' },
    { value: 'Tribunal de Justiça - Mato Grosso do Sul', label: 'Tribunal de Justiça - Mato Grosso do Sul' },
    { value: 'Tribunal de Justiça - Minas Gerais', label: 'Tribunal de Justiça - Minas Gerais' },
    { value: 'Tribunal de Justiça - Paraná', label: 'Tribunal de Justiça - Paraná' },
    { value: 'Tribunal de Justiça - Paraíba', label: 'Tribunal de Justiça - Paraíba' },
    { value: 'Tribunal de Justiça - Pará', label: 'Tribunal de Justiça - Pará' },
    { value: 'Tribunal de Justiça - Pernambuco', label: 'Tribunal de Justiça - Pernambuco' },
    { value: 'Tribunal de Justiça - Piauí', label: 'Tribunal de Justiça - Piauí' },
    { value: 'Tribunal de Justiça - Rio Grande do Norte', label: 'Tribunal de Justiça - Rio Grande do Norte' },
    { value: 'Tribunal de Justiça - Rio Grande do Sul', label: 'Tribunal de Justiça - Rio Grande do Sul' },
    { value: 'Tribunal de Justiça - Rio de Janeiro', label: 'Tribunal de Justiça - Rio de Janeiro' },
    { value: 'Tribunal de Justiça - Rondônia', label: 'Tribunal de Justiça - Rondônia' },
    { value: 'Tribunal de Justiça - Roraima', label: 'Tribunal de Justiça - Roraima' },
    { value: 'Tribunal de Justiça - Santa Catarina', label: 'Tribunal de Justiça - Santa Catarina' },
    { value: 'Tribunal de Justiça - Sergipe', label: 'Tribunal de Justiça - Sergipe' },
    { value: 'Tribunal de Justiça - São Paulo', label: 'Tribunal de Justiça - São Paulo' },
    { value: 'Tribunal de Justiça - Tocantins', label: 'Tribunal de Justiça - Tocantins' },
    { value: 'Tribunal Regional Federal da 1ª Região', label: 'Tribunal Regional Federal da 1ª Região' },
    { value: 'Tribunal Regional Federal da 2ª Região', label: 'Tribunal Regional Federal da 2ª Região' },
    { value: 'Tribunal Regional Federal da 3ª Região', label: 'Tribunal Regional Federal da 3ª Região' },
    { value: 'Tribunal Regional Federal da 4ª Região', label: 'Tribunal Regional Federal da 4ª Região' },
    { value: 'Tribunal Regional Federal da 5ª Região', label: 'Tribunal Regional Federal da 5ª Região' },
    { value: 'TRT da 1ª Região - Rio de Janeiro', label: 'TRT da 1ª Região - Rio de Janeiro' },
    { value: 'TRT da 2ª Região - São Paulo', label: 'TRT da 2ª Região - São Paulo' },
    { value: 'TRT da 3ª Região - Minas Gerais', label: 'TRT da 3ª Região - Minas Gerais' },
    { value: 'TRT da 4ª Região - Rio Grande do Sul', label: 'TRT da 4ª Região - Rio Grande do Sul' },
    { value: 'TRT da 5ª Região - Bahia', label: 'TRT da 5ª Região - Bahia' },
    { value: 'TRT da 6ª Região - Pernambuco', label: 'TRT da 6ª Região - Pernambuco' },
    { value: 'TRT da 7ª Região - Ceará', label: 'TRT da 7ª Região - Ceará' },
    { value: 'TRT da 8ª Região - Pará e Amapá', label: 'TRT da 8ª Região - Pará e Amapá' },
    { value: 'TRT da 9ª Região - Paraná', label: 'TRT da 9ª Região - Paraná' },
    { value: 'TRT da 10ª Região - Distrito Federal e Tocantins', label: 'TRT da 10ª Região - Distrito Federal e Tocantins' },
    { value: 'TRT da 11ª Região - Amazonas e Roraima', label: 'TRT da 11ª Região - Amazonas e Roraima' },
    { value: 'TRT da 12ª Região - Santa Catarina', label: 'TRT da 12ª Região - Santa Catarina' },
    { value: 'TRT da 13ª Região - Paraíba', label: 'TRT da 13ª Região - Paraíba' },
    { value: 'TRT da 14ª Região - Acre e Rondônia', label: 'TRT da 14ª Região - Acre e Rondônia' },
    { value: 'TRT da 15ª Região - Sao Paulo/Campinas', label: 'TRT da 15ª Região - Sao Paulo/Campinas' },
    { value: 'TRT da 16ª Região - Maranhão', label: 'TRT da 16ª Região - Maranhão' },
    { value: 'TRT da 17ª Região - Espírito Santo', label: 'TRT da 17ª Região - Espírito Santo' },
    { value: 'TRT da 18ª Região - Goiás', label: 'TRT da 18ª Região - Goiás' },
    { value: 'TRT da 19ª Região - Alagoas', label: 'TRT da 19ª Região - Alagoas' },
    { value: 'TRT da 20ª Região - Sergipe', label: 'TRT da 20ª Região - Sergipe' },
    { value: 'TRT da 21ª Região - Rio Grande do Norte', label: 'TRT da 21ª Região - Rio Grande do Norte' },
    { value: 'TRT da 22ª Região - Piauí', label: 'TRT da 22ª Região - Piauí' },
    { value: 'TRT da 23ª Região - Mato Grosso', label: 'TRT da 23ª Região - Mato Grosso' },
    { value: 'TRT da 24ª Região - Mato Grosso do Sul', label: 'TRT da 24ª Região - Mato Grosso do Sul' },
    { value: 'Tribunal Regional Eleitoral - Acre', label: 'Tribunal Regional Eleitoral - Acre' },
    { value: 'Tribunal Regional Eleitoral - Alagoas', label: 'Tribunal Regional Eleitoral - Alagoas' },
    { value: 'Tribunal Regional Eleitoral - Amapá', label: 'Tribunal Regional Eleitoral - Amapá' },
    { value: 'Tribunal Regional Eleitoral - Amazonas', label: 'Tribunal Regional Eleitoral - Amazonas' },
    { value: 'Tribunal Regional Eleitoral - Bahia', label: 'Tribunal Regional Eleitoral - Bahia' },
    { value: 'Tribunal Regional Eleitoral - Ceará', label: 'Tribunal Regional Eleitoral - Ceará' },
    { value: 'Tribunal Regional Eleitoral - Distrito Federal', label: 'Tribunal Regional Eleitoral - Distrito Federal' },
    { value: 'Tribunal Regional Eleitoral - Espírito Santo', label: 'Tribunal Regional Eleitoral - Espírito Santo' },
    { value: 'Tribunal Regional Eleitoral - Goiás', label: 'Tribunal Regional Eleitoral - Goiás' },
    { value: 'Tribunal Regional Eleitoral - Maranhão', label: 'Tribunal Regional Eleitoral - Maranhão' },
    { value: 'Tribunal Regional Eleitoral - Mato Grosso', label: 'Tribunal Regional Eleitoral - Mato Grosso' },
    { value: 'Tribunal Regional Eleitoral - Mato Grosso do Sul', label: 'Tribunal Regional Eleitoral - Mato Grosso do Sul' },
    { value: 'Tribunal Regional Eleitoral - Minas Gerais', label: 'Tribunal Regional Eleitoral - Minas Gerais' },
    { value: 'Tribunal Regional Eleitoral - Paraná', label: 'Tribunal Regional Eleitoral - Paraná' },
    { value: 'Tribunal Regional Eleitoral - Paraíba', label: 'Tribunal Regional Eleitoral - Paraíba' },
    { value: 'Tribunal Regional Eleitoral - Pará', label: 'Tribunal Regional Eleitoral - Pará' },
    { value: 'Tribunal Regional Eleitoral - Pernambuco', label: 'Tribunal Regional Eleitoral - Pernambuco' },
    { value: 'Tribunal Regional Eleitoral - Piauí', label: 'Tribunal Regional Eleitoral - Piauí' },
    { value: 'Tribunal Regional Eleitoral - Rio Grande do Norte', label: 'Tribunal Regional Eleitoral - Rio Grande do Norte' },
    { value: 'Tribunal Regional Eleitoral - Rio Grande do Sul', label: 'Tribunal Regional Eleitoral - Rio Grande do Sul' },
    { value: 'Tribunal Regional Eleitoral - Rio de Janeiro', label: 'Tribunal Regional Eleitoral - Rio de Janeiro' },
    { value: 'Tribunal Regional Eleitoral - Rondônia', label: 'Tribunal Regional Eleitoral - Rondônia' },
    { value: 'Tribunal Regional Eleitoral - Roraima', label: 'Tribunal Regional Eleitoral - Roraima' },
    { value: 'Tribunal Regional Eleitoral - Santa Catarina', label: 'Tribunal Regional Eleitoral - Santa Catarina' },
    { value: 'Tribunal Regional Eleitoral - Sergipe', label: 'Tribunal Regional Eleitoral - Sergipe' },
    { value: 'Tribunal Regional Eleitoral - São Paulo', label: 'Tribunal Regional Eleitoral - São Paulo' },
    { value: 'Tribunal Regional Eleitoral - Tocantins', label: 'Tribunal Regional Eleitoral - Tocantins' },
    { value: 'Tribunal de Justiça Militar do Estado de São Paulo', label: 'Tribunal de Justiça Militar do Estado de São Paulo' },
    { value: 'Tribunal de Justiça Militar do Estado do Rio Grande do Sul', label: 'Tribunal de Justiça Militar do Estado do Rio Grande do Sul' },
    { value: 'Superior Tribunal do Trabalho', label: 'Superior Tribunal do Trabalho' },
    { value: 'Superior Tribunal Eleitoral', label: 'Superior Tribunal Eleitoral' },
    { value: 'Superior Tribunal Militar', label: 'Superior Tribunal Militar' },
    { value: 'Superior Tribunal de Justiça', label: 'Superior Tribunal de Justiça' },
    { value: 'Supremo Tribunal Federal', label: 'Supremo Tribunal Federal' },
];

export const STATUS_EVENTO_OPTIONS = [
    { value: 'AGENDADO', label: 'Agendado' },
    { value: 'CONCLUIDO', label: 'Concluído' },
    { value: 'CANCELADO', label: 'Cancelado' },
];

export const COMO_CONHECEU_OPTIONS = [
    { value: 'ANUNCIO', label: 'Anúncio' },
    { value: 'FAMILIA_AMIGO', label: 'É família/Amigo' },
    { value: 'GOOGLE', label: 'Google' },
    { value: 'INDICACAO', label: 'Indicação' },
    { value: 'OUTROS', label: 'Outros' },
    { value: 'PARCERIA', label: 'Parceria' },
    { value: 'REDES_SOCIAIS', label: 'Redes sociais' },
    { value: 'SITE', label: 'Site' },
];
  
export const SIM_NAO_OPTIONS = [
    { value: 'SIM', label: 'Sim' },
    { value: 'NAO', label: 'Não' },
];

export const TIPO_RECEBIMENTO_OPTIONS = [
    { value: 'COMISSAO', label: 'Comissão' },
    { value: 'CONSULTA', label: 'Consulta' },
    { value: 'ENTRADA', label: 'Entrada' },
    { value: 'HONORARIOS', label: 'Honorários' },
    { value: 'MENSALIDADE', label: 'Mensalidade' },
    { value: 'MULTA', label: 'Multa' },
    { value: 'OUTROS', label: 'Outros' },
];

export const CATEGORIA_DESPESA_OPTIONS = [
    { value: 'AGUA', label: 'Água' },
    { value: 'ALIMENTACAO', label: 'Alimentação' },
    { value: 'ALUGUEL', label: 'Aluguel' },
    { value: 'CELULAR', label: 'Celular' },
    { value: 'COMPRAS', label: 'Compras' },
    { value: 'GAS', label: 'Gás' },
    { value: 'INTERNET', label: 'Internet' },
    { value: 'INVESTIMENTO', label: 'Investimento' },
    { value: 'LIMPEZA', label: 'Limpeza' },
    { value: 'LUZ', label: 'Luz' },
    { value: 'MANUTENCAO', label: 'Manutenção' },
    { value: 'MATERIAIS', label: 'Materiais' },
    { value: 'MERCADO', label: 'Mercado' },
    { value: 'OUTRAS', label: 'Outras' },
    { value: 'OUTRAS_DESPESAS_FUNCIONARIO', label: 'Outras Despesas com Funcionário' },
    { value: 'PUBLICIDADE', label: 'Publicidade' },
    { value: 'SALARIO_FUNCIONARIO', label: 'Salário de Funcionário' },
    { value: 'TRANSPORTE', label: 'Transporte' },
];

export const STATUS_TAREFA_OPTIONS = [
    { value: 'NAO_INICIADA', label: 'Não iniciada' },
    { value: 'EM_ANDAMENTO', label: 'Em andamento' },
    { value: 'CONCLUIDA', label: 'Concluída' },
];

export const URGENCIA_TAREFA_OPTIONS = [
    { value: 'EXIGE_ATENCAO_IMEDIATA', label: 'Exige atenção imediata' },
    { value: 'MUITO_URGENTE', label: 'Muito urgente' },
    { value: 'REQUER_ATENCAO', label: 'Requer atenção' },
    { value: 'POUCO_URGENTE', label: 'Pouco urgente' },
    { value: 'PODE_ESPERAR', label: 'Pode esperar' },
];