quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/sistema_advocacia?useSSL=false&serverTimezone=UTC

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.encrypt.key.location=publicKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

smallrye.jwt.new-token.lifespan=86400

quarkus.log.level=INFO
quarkus.log.category."com.advocacia".level=DEBUG